### ISSUE TITLE
tinyws for commonJS

### ISSUE THREAD

**Issue by franckOL** [tinyhttp/tinyws#3]
is there a way to use tinyws in commonJS. I got some legacy code.

**Comment by talentlessguy** [comment]
I guess transpiling node_modules is a way

**Comment by franckOL** [comment]
You suggest to modify my code :-).

**Comment by franckOL** [comment]
I try to investage hybryd npm packahe looking at https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html. But not enough skills on my side

**Comment by talentlessguy** [comment]
@franckOL that's a different topic. the article is about module creators. you're a module user

so there are two ways:
- running code through cjstoesm
- doing some magic to transpile node_modules

**Comment by fwouts** [comment]
@talentlessguy Is there any particular reason not to provide both CJS and ESM versions in your published module, to ease adoption?

**Comment by talentlessguy** [comment]
@fwouts providing both versions adds maintenance burden, increases chance to get CJS-specific bugs and also CJS is not a JavaScript standard
