### ISSUE TITLE
Express example?

### ISSUE THREAD

**Issue by aknoerig** [tinyhttp/tinyws#5]
Could you provide an example on how to use this with `express` instead of `tinyhttp`?

Since `express.Application` does not support generics, I can't figure out how to make the ts-compiler accept `app.use(tinyws())` -- it doesn't accept `TinyWSRequest` as a parameter.

**Comment by aknoerig** [comment]
One way to fix it seems to be making `TinyWSRequest` extend `express.Request` instead of `http.IncomingMessage`.

Not sure if there's a way to make this compatible for `tinyhttp` at the same time, though..

**Comment by talentlessguy** [comment]
try with

```ts
declare module 'express' {
  interface Request { ... }
}
```

**Comment by simonbowen** [comment]
I came here from your comment on express-ws and attempted to use the example on the thread there, it doesn't work. 

Is it possible to get an updated example for usage with express?

**Comment by danieldunderfelt** [comment]
> try with
> 
> ```ts
> declare module 'express' {
>   interface Request { ... }
> }
> ```

I'm not sure what to do with this. Can you elaborate? It seems you left out the crucial part.

> in which way it doesn't work?

It's not compatible as an Express middleware.

```
app.use(tinyws())
```
=
```
TS2769: No overload matches this call.
 The last overload gave the following error. 
   Argument of type '(req: TinyWSRequest, _: unknown, next: () => void | Promise<void>) => Promise<void>' is not assignable to parameter of type 'PathParams'.
     Type '(req: TinyWSRequest, _: unknown, next: () => void | Promise<void>) => Promise<void>' is missing the following properties from type '(string | RegExp)[]': pop, push, concat, join, and 28 more. 
```
